[2025-11-01T14:02:15.162+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_test_linktx manual__2025-11-01T13:57:11.352288+00:00 [queued]>
[2025-11-01T14:02:15.175+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_test_linktx manual__2025-11-01T13:57:11.352288+00:00 [queued]>
[2025-11-01T14:02:15.176+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T14:02:15.189+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_test_linktx> on 2025-11-01 13:57:11.352288+00:00
[2025-11-01T14:02:15.195+0000] {standard_task_runner.py:60} INFO - Started process 3778 to run task
[2025-11-01T14:02:15.199+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_test_linktx', 'manual__2025-11-01T13:57:11.352288+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmp29esoejq']
[2025-11-01T14:02:15.201+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask dbt_test_linktx
[2025-11-01T14:02:15.274+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_test_linktx manual__2025-11-01T13:57:11.352288+00:00 [running]> on host 0e882971ff2e
[2025-11-01T14:02:15.378+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_test_linktx' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T13:57:11.352288+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T13:57:11.352288+00:00'
[2025-11-01T14:02:15.381+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-11-01T14:02:15.383+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt --no-use-colors test --project-dir /opt/***/dbt_project --profiles-dir /opt/***/dbt_project --select silver_link_transactions']
[2025-11-01T14:02:15.395+0000] {subprocess.py:86} INFO - Output:
[2025-11-01T14:02:15.396+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-11-01T14:02:15.397+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-11-01T14:02:15.411+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-11-01T14:02:15.414+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_test_linktx, execution_date=20251101T135711, start_date=20251101T140215, end_date=20251101T140215
[2025-11-01T14:02:15.431+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task dbt_test_linktx (Bash command failed. The command returned a non-zero exit code 127.; 3778)
[2025-11-01T14:02:15.452+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T14:02:15.481+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
