[2025-10-31T23:12:28.129+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T23:12:23.731239+00:00 [queued]>
[2025-10-31T23:12:28.143+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T23:12:23.731239+00:00 [queued]>
[2025-10-31T23:12:28.144+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-31T23:12:28.169+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): silver_dbt.dbt_run_incrementals> on 2025-10-31 23:12:23.731239+00:00
[2025-10-31T23:12:28.176+0000] {standard_task_runner.py:60} INFO - Started process 1492 to run task
[2025-10-31T23:12:28.183+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestion_pipeline', 'silver_dbt.dbt_run_incrementals', 'manual__2025-10-31T23:12:23.731239+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmp93tvc28q']
[2025-10-31T23:12:28.186+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask silver_dbt.dbt_run_incrementals
[2025-10-31T23:12:28.322+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T23:12:23.731239+00:00 [running]> on host ad620feb6bee
[2025-10-31T23:12:28.457+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_pipeline' AIRFLOW_CTX_TASK_ID='silver_dbt.dbt_run_incrementals' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T23:12:23.731239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T23:12:23.731239+00:00'
[2025-10-31T23:12:28.459+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:12:28.462+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec -i dbt bash -lc \'\nset -e\ncd /dbt\nDBT_VARS=$(python - <<"PY"\nfrom datetime import datetime, timedelta\nimport json\nds = "2025-10-31"\nlag_days = 0\nlagged = (datetime.strptime(ds, "%Y-%m-%d") - timedelta(days=lag_days)).strftime("%Y-%m-%d")\nprint(json.dumps({"ds_lagged": lagged}))\nPY\n)\necho "dbt vars => ${DBT_VARS}"\ndbt --no-use-colors run --profiles-dir /dbt --select silver_payments silver_link_transactions --vars "${DBT_VARS}"\n\'']
[2025-10-31T23:12:28.472+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T23:12:28.613+0000] {subprocess.py:93} INFO - dbt vars => {"ds_lagged": "2025-10-31"}
[2025-10-31T23:12:30.251+0000] {subprocess.py:93} INFO - 23:12:30  Running with dbt=1.10.13
[2025-10-31T23:12:30.519+0000] {subprocess.py:93} INFO - 23:12:30  Registered adapter: clickhouse=1.9.5
[2025-10-31T23:12:31.290+0000] {subprocess.py:93} INFO - 23:12:31  Found 3 models, 3 sources, 491 macros
[2025-10-31T23:12:31.296+0000] {subprocess.py:93} INFO - 23:12:31
[2025-10-31T23:12:31.297+0000] {subprocess.py:93} INFO - 23:12:31  Concurrency: 4 threads (target='dev')
[2025-10-31T23:12:31.299+0000] {subprocess.py:93} INFO - 23:12:31
[2025-10-31T23:12:31.619+0000] {subprocess.py:93} INFO - 23:12:31  1 of 2 START sql incremental model `silver`.`silver_link_transactions` ......... [RUN]
[2025-10-31T23:12:31.620+0000] {subprocess.py:93} INFO - 23:12:31  2 of 2 START sql incremental model `silver`.`silver_payments` .................. [RUN]
[2025-10-31T23:12:31.749+0000] {subprocess.py:93} INFO - 23:12:31  2 of 2 ERROR creating sql incremental model `silver`.`silver_payments` ......... [ERROR in 0.12s]
[2025-10-31T23:12:31.751+0000] {subprocess.py:93} INFO - 23:12:31  1 of 2 ERROR creating sql incremental model `silver`.`silver_link_transactions`  [ERROR in 0.13s]
[2025-10-31T23:12:31.768+0000] {subprocess.py:93} INFO - 23:12:31
[2025-10-31T23:12:31.769+0000] {subprocess.py:93} INFO - 23:12:31  Finished running 2 incremental models in 0 hours 0 minutes and 0.47 seconds (0.47s).
[2025-10-31T23:12:31.834+0000] {subprocess.py:93} INFO - 23:12:31
[2025-10-31T23:12:31.835+0000] {subprocess.py:93} INFO - 23:12:31  Completed with 2 errors, 0 partial successes, and 0 warnings:
[2025-10-31T23:12:31.836+0000] {subprocess.py:93} INFO - 23:12:31
[2025-10-31T23:12:31.838+0000] {subprocess.py:93} INFO - 23:12:31  Failure in model silver_payments (models/silver/silver_payments.sql)
[2025-10-31T23:12:31.839+0000] {subprocess.py:93} INFO - 23:12:31    Compilation Error in model silver_payments (models/silver/silver_payments.sql)
[2025-10-31T23:12:31.840+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-10-31T23:12:31.840+0000] {subprocess.py:93} INFO - 
[2025-10-31T23:12:31.841+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-10-31T23:12:31.842+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T23:12:31.843+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T23:12:31.843+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-10-31T23:12:31.844+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-10-31T23:12:31.844+0000] {subprocess.py:93} INFO -   > called by model silver_payments (models/silver/silver_payments.sql)
[2025-10-31T23:12:31.845+0000] {subprocess.py:93} INFO - 23:12:31
[2025-10-31T23:12:31.846+0000] {subprocess.py:93} INFO - 23:12:31    compiled code at target/compiled/ck_project/models/silver/silver_payments.sql
[2025-10-31T23:12:31.847+0000] {subprocess.py:93} INFO - 23:12:31
[2025-10-31T23:12:31.847+0000] {subprocess.py:93} INFO - 23:12:31  Failure in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-10-31T23:12:31.848+0000] {subprocess.py:93} INFO - 23:12:31    Compilation Error in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-10-31T23:12:31.849+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-10-31T23:12:31.849+0000] {subprocess.py:93} INFO - 
[2025-10-31T23:12:31.850+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-10-31T23:12:31.851+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T23:12:31.851+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T23:12:31.852+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-10-31T23:12:31.853+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-10-31T23:12:31.853+0000] {subprocess.py:93} INFO -   > called by model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-10-31T23:12:31.854+0000] {subprocess.py:93} INFO - 23:12:31
[2025-10-31T23:12:31.854+0000] {subprocess.py:93} INFO - 23:12:31    compiled code at target/compiled/ck_project/models/silver/silver_link_transactions.sql
[2025-10-31T23:12:31.854+0000] {subprocess.py:93} INFO - 23:12:31
[2025-10-31T23:12:31.855+0000] {subprocess.py:93} INFO - 23:12:31  Done. PASS=0 WARN=0 ERROR=2 SKIP=0 NO-OP=0 TOTAL=2
[2025-10-31T23:12:32.802+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:12:32.815+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:12:32.818+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestion_pipeline, task_id=silver_dbt.dbt_run_incrementals, execution_date=20251031T231223, start_date=20251031T231228, end_date=20251031T231232
[2025-10-31T23:12:32.839+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task silver_dbt.dbt_run_incrementals (Bash command failed. The command returned a non-zero exit code 1.; 1492)
[2025-10-31T23:12:32.858+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T23:12:32.878+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
