[2025-10-31T22:52:10.208+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-10-31T22:46:59.945189+00:00 [queued]>
[2025-10-31T22:52:10.224+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-10-31T22:46:59.945189+00:00 [queued]>
[2025-10-31T22:52:10.225+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-10-31T22:52:10.243+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): silver_dbt.dbt_run_merchants> on 2025-10-31 22:46:59.945189+00:00
[2025-10-31T22:52:10.253+0000] {standard_task_runner.py:60} INFO - Started process 778 to run task
[2025-10-31T22:52:10.259+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestion_pipeline', 'silver_dbt.dbt_run_merchants', 'manual__2025-10-31T22:46:59.945189+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpz5vqfhbp']
[2025-10-31T22:52:10.262+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask silver_dbt.dbt_run_merchants
[2025-10-31T22:52:10.357+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-10-31T22:46:59.945189+00:00 [running]> on host d335ca5d7801
[2025-10-31T22:52:10.466+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_pipeline' AIRFLOW_CTX_TASK_ID='silver_dbt.dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T22:46:59.945189+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T22:46:59.945189+00:00'
[2025-10-31T22:52:10.470+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T22:52:10.472+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec -i dbt bash -lc \'set -e; docker exec -i clickhouse-server clickhouse-client -q "CREATE DATABASE IF NOT EXISTS silver;"; set +e; cd /dbt && dbt --no-use-colors run --profiles-dir /dbt --select silver_merchants --full-refresh; RC=$?; if [ $RC -ne 0 ]; then   echo "[silver/dbt] WARNING: silver_merchants failed (rc=$RC). Skipping this step and continuing the pipeline.";   # Optional: show compiled SQL path for quick debugging (if it exists)\n  test -d target/compiled &&   echo "[silver/dbt] See compiled SQL under target/compiled/";   exit 0; fi; exit 0;\'']
[2025-10-31T22:52:10.482+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T22:52:10.607+0000] {subprocess.py:93} INFO - bash: line 1: docker: command not found
[2025-10-31T22:52:10.615+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-10-31T22:52:10.633+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-31T22:52:10.639+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingestion_pipeline, task_id=silver_dbt.dbt_run_merchants, execution_date=20251031T224659, start_date=20251031T225210, end_date=20251031T225210
[2025-10-31T22:52:10.655+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task silver_dbt.dbt_run_merchants (Bash command failed. The command returned a non-zero exit code 127.; 778)
[2025-10-31T22:52:10.672+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T22:52:10.696+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
