[2025-11-01T13:57:13.330+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T13:57:11.352288+00:00 [queued]>
[2025-11-01T13:57:13.342+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T13:57:11.352288+00:00 [queued]>
[2025-11-01T13:57:13.342+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T13:57:13.359+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run_linktx> on 2025-11-01 13:57:11.352288+00:00
[2025-11-01T13:57:13.365+0000] {standard_task_runner.py:60} INFO - Started process 3466 to run task
[2025-11-01T13:57:13.370+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_linktx', 'manual__2025-11-01T13:57:11.352288+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmp89o4wjc9']
[2025-11-01T13:57:13.373+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask dbt_run_linktx
[2025-11-01T13:57:13.459+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T13:57:11.352288+00:00 [running]> on host 0e882971ff2e
[2025-11-01T13:57:13.593+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_linktx' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T13:57:11.352288+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T13:57:11.352288+00:00'
[2025-11-01T13:57:13.595+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-11-01T13:57:13.598+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt --no-use-colors run --project-dir /opt/***/dbt_project --profiles-dir /opt/***/dbt_project --select silver_link_transactions --vars \'{"ds_lagged":"$DS_LAGGED"}\'']
[2025-11-01T13:57:13.612+0000] {subprocess.py:86} INFO - Output:
[2025-11-01T13:57:13.621+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-11-01T13:57:13.622+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-11-01T13:57:13.637+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-11-01T13:57:13.641+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_run_linktx, execution_date=20251101T135711, start_date=20251101T135713, end_date=20251101T135713
[2025-11-01T13:57:13.658+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 32 for task dbt_run_linktx (Bash command failed. The command returned a non-zero exit code 127.; 3466)
[2025-11-01T13:57:13.703+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T13:57:13.752+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
