[2025-11-01T19:31:54.554+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T19:31:52.421379+00:00 [queued]>
[2025-11-01T19:31:54.569+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T19:31:52.421379+00:00 [queued]>
[2025-11-01T19:31:54.570+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T19:31:54.587+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run_merchants> on 2025-11-01 19:31:52.421379+00:00
[2025-11-01T19:31:54.596+0000] {standard_task_runner.py:60} INFO - Started process 11005 to run task
[2025-11-01T19:31:54.601+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_merchants', 'manual__2025-11-01T19:31:52.421379+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmpiu38g36h']
[2025-11-01T19:31:54.605+0000] {standard_task_runner.py:88} INFO - Job 202: Subtask dbt_run_merchants
[2025-11-01T19:31:54.696+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T19:31:52.421379+00:00 [running]> on host 69cecc54c654
[2025-11-01T19:31:54.824+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T19:31:52.421379+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T19:31:52.421379+00:00'
[2025-11-01T19:31:59.633+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/silver_dag.py", line 191, in <lambda>
    python_callable=lambda ds, **_: _run_dbt("silver_merchants", ds=ds, full_refresh=True, pass_ds_lagged=True),
  File "/opt/airflow/dags/silver_dag.py", line 149, in _run_dbt
    raise RuntimeError(f"dbt failed ({proc.returncode}).\nSTDOUT:\n{proc.stdout}\n\nSTDERR:\n{proc.stderr}")
RuntimeError: dbt failed (1).
STDOUT:
19:31:57  Running with dbt=1.5.9
19:31:57  Registered adapter: clickhouse=1.5.2
19:31:58  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 349 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
19:31:58  
19:31:58  Concurrency: 4 threads (target='dev')
19:31:58  
19:31:58  1 of 1 START sql incremental model silver.silver_merchants ..................... [RUN]
19:31:58  1 of 1 ERROR creating sql incremental model silver.silver_merchants ............ [ERROR in 0.16s]
19:31:58  
19:31:58  Finished running 1 incremental model in 0 hours 0 minutes and 0.52 seconds (0.52s).
19:31:58  
19:31:58  Completed with 1 error and 0 warnings:
19:31:58  
19:31:58  Database Error in model silver_merchants (models/silver/silver_merchants.sql)
19:31:58    Code: 370.
19:31:58    DB::Exception: Data type Nullable(Nothing) of column 'merchant_id' cannot be used in tables. Stack trace:
19:31:58    
19:31:58    0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000137a855f
19:31:58    1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000cae7e8e
19:31:58    2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cae7940
19:31:58    3. DB::Exception::Exception<String, String const&>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String const&>::type>, String&&, String const&) @ 0x000000000d28126b
19:31:58    4. DB::checkAllTypesAreAllowedInTable(DB::NamesAndTypesList const&) @ 0x0000000018e402bb
19:31:58    5. DB::StorageFactory::get(DB::ASTCreateQuery const&, String const&, std::shared_ptr<DB::Context>, std::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, DB::LoadingStrictnessLevel, bool) const @ 0x0000000018e40952
19:31:58    6. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel) @ 0x00000000182fb075
19:31:58    7. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x00000000182ef810
19:31:58    8. DB::InterpreterCreateQuery::execute() @ 0x0000000018303978
19:31:58    9. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x0000000018780440
19:31:58    10. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000187786cb
19:31:58    11. DB::TCPHandler::runImpl() @ 0x0000000019e2d3db
19:31:58    12. DB::TCPHandler::run() @ 0x0000000019e4f119
19:31:58    13. Poco::Net::TCPServerConnection::start() @ 0x000000001ef4ed07
19:31:58    14. Poco::Net::TCPServerDispatcher::run() @ 0x000000001ef4f199
19:31:58    15. Poco::PooledThread::run() @ 0x000000001ef15b87
19:31:58    16. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001ef13f81
19:31:58    17. ? @ 0x0000000000094ac3
19:31:58    18. ? @ 0x0000000000125a74
19:31:58  
19:31:58  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1


STDERR:

[2025-11-01T19:31:59.657+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_run_merchants, execution_date=20251101T193152, start_date=20251101T193154, end_date=20251101T193159
[2025-11-01T19:31:59.694+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 202 for task dbt_run_merchants (dbt failed (1).
STDOUT:
19:31:57  Running with dbt=1.5.9
19:31:57  Registered adapter: clickhouse=1.5.2
19:31:58  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 349 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
19:31:58  
19:31:58  Concurrency: 4 threads (target='dev')
19:31:58  
19:31:58  1 of 1 START sql incremental model silver.silver_merchants ..................... [RUN]
19:31:58  1 of 1 ERROR creating sql incremental model silver.silver_merchants ............ [ERROR in 0.16s]
19:31:58  
19:31:58  Finished running 1 incremental model in 0 hours 0 minutes and 0.52 seconds (0.52s).
19:31:58  
19:31:58  Completed with 1 error and 0 warnings:
19:31:58  
19:31:58  Database Error in model silver_merchants (models/silver/silver_merchants.sql)
19:31:58    Code: 370.
19:31:58    DB::Exception: Data type Nullable(Nothing) of column 'merchant_id' cannot be used in tables. Stack trace:
19:31:58    
19:31:58    0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000137a855f
19:31:58    1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000cae7e8e
19:31:58    2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cae7940
19:31:58    3. DB::Exception::Exception<String, String const&>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String const&>::type>, String&&, String const&) @ 0x000000000d28126b
19:31:58    4. DB::checkAllTypesAreAllowedInTable(DB::NamesAndTypesList const&) @ 0x0000000018e402bb
19:31:58    5. DB::StorageFactory::get(DB::ASTCreateQuery const&, String const&, std::shared_ptr<DB::Context>, std::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, DB::LoadingStrictnessLevel, bool) const @ 0x0000000018e40952
19:31:58    6. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel) @ 0x00000000182fb075
19:31:58    7. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x00000000182ef810
19:31:58    8. DB::InterpreterCreateQuery::execute() @ 0x0000000018303978
19:31:58    9. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x0000000018780440
19:31:58    10. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000187786cb
19:31:58    11. DB::TCPHandler::runImpl() @ 0x0000000019e2d3db
19:31:58    12. DB::TCPHandler::run() @ 0x0000000019e4f119
19:31:58    13. Poco::Net::TCPServerConnection::start() @ 0x000000001ef4ed07
19:31:58    14. Poco::Net::TCPServerDispatcher::run() @ 0x000000001ef4f199
19:31:58    15. Poco::PooledThread::run() @ 0x000000001ef15b87
19:31:58    16. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001ef13f81
19:31:58    17. ? @ 0x0000000000094ac3
19:31:58    18. ? @ 0x0000000000125a74
19:31:58  
19:31:58  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1


STDERR:
; 11005)
[2025-11-01T19:31:59.723+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T19:31:59.757+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
